update

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -27,8 +27,16 @@ jobs:
 
       - name: Change to Project Directory
         run: |
+          echo "Contents of the root directory:"
           ls
-          cd duman_app
+          if [ -d "duman_app" ]; then
+            cd duman_app
+            echo "Changed to duman_app directory. Contents:"
+            ls
+          else
+            echo "Directory duman_app not found."
+            exit 1
+          fi
 
       - name: Get dependencies
         run: flutter pub get
